### ISSUE TITLE
Demo Repo (from README)

### ISSUE THREAD

**Issue by tacman** [webfactory/WebfactoryPolyglotBundle#64]
I've created a demo repo from the README instructions.  Basically 

```
symfony new ...
require the bundle
create the entity classes from the readme
create a fixtures file to load entities
```

I've added the classes (Document and DocumentTranslations) from README almost exactly (I tweaked the classes so they'd compile). And create a fixtures file.

This uses sqlite, so these 4 lines should show the error. It's using dev-master of the polyglot-bundle

git clone git@github.com:survos-sites/polyglot-readme.git && cd polyglot-readme
composer install
bin/console doctrine:schema:update --force
bin/console doctrine:fixtures:load -n 
                                                                                               

   > purging database
   > loading App\DataFixtures\App
   > loading App\DataFixtures\AppFixtures

In CacheItem.php line 139:
                                                                                               
  Cache key "App\Entity\Document$WebfactoryPolyglot" contains reserved characters "{}()/\@:".  
                                                                                               

doctrine:fixtures:load [--append] [--group GROUP] [--em EM] [--purger PURGER] [--purge-exclusions PURGE-EXCLUSIONS] [--purge-with-truncate]

Any chance somebody could take a look at it?  When it works, it'll be a nice example for someone who wants to see it in action.

**Comment by mpdude** [comment]
I have made some suggestions and extensions in https://github.com/survos-sites/polyglot-readme/pull/1

**Comment by tacman** [comment]
The demo repo works now, thanks!
